batch_size: 10
val_batch_size: 8
epochs: 50
base_dir: "/home/fi5666wi/Documents/Prostate images/unlabeled"
save_dir: "/home/fi5666wi/Documents/Python/saved_models/hu_clr"
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 10
weight_decay: 10e-6
img_size: 64
val_split: 0.1
input_shape: (3,256,256)
model:
  out_dim: 256
  embed_dim: 512
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (112,112,3)
  num_workers: 0
  valid_size: 0.01

loss:
  temperature: 0.5
  use_cosine_similarity: True
